config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  root 'home#index'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/role.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: roles
#
#  id                            :bigint           not null, primary key
#  name(Повна назва)             :string
#  slug(Корока назва/позначення) :string
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#
# Indexes
#
#  index_roles_on_slug  (slug) UNIQUE
#
class Role < ApplicationRecord
  has_many :users, dependent: :nullify

  validates :name, presence: true
  validates :slug, presence: true, uniqueness: true, length: { maximum: 10 }
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                               :bigint           not null, primary key
#  email                            :string           default(""), not null
#  encrypted_password               :string           default(""), not null
#  full_name                        :string           default(""), not null
#  remember_created_at              :datetime
#  reset_password_sent_at           :datetime
#  reset_password_token             :string
#  created_at                       :datetime         not null
#  updated_at                       :datetime         not null
#  role_id(Додано роль користувачу) :bigint           not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_role_id               (role_id)
#
# Foreign Keys
#
#  fk_rails_...  (role_id => roles.id)
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  :omniauthable, omniauth_providers: [:google]
  belongs_to :role, optional: true
  before_create :set_default_role

  # validates :full_name, length: { minimum: 2, maximum: 50 }

  private

  def set_default_role
    self.role ||= Role.find_by(slug: 'default')
  end
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

module Admin
  class ApplicationController < ::ApplicationController; end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_admin_user, only: %i[show edit update destroy]

    # GET /admin/users
    def index
      @admin_users = User.all
    end

    # GET /admin/users/1
    def show; end

    # GET /admin/users/new
    def new
      @admin_user = Admin::User.new
    end

    # GET /admin/users/1/edit
    def edit; end

    # POST /admin/users
    def create
      @admin_user = Admin::User.new(admin_user_params)

      if @admin_user.save
        redirect_to @admin_user, notice: 'User was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /admin/users/1
    def update
      if @admin_user.update(admin_user_params)
        redirect_to @admin_user, notice: 'User was successfully updated.', status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /admin/users/1
    def destroy
      @admin_user.destroy!
      redirect_to admin_users_url, notice: 'User was successfully destroyed.', status: :see_other
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_user_params
      params.fetch(:admin_user, {})
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    # код для домашньої сторінки
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/users/_form.html.slim
= form_with(model: admin_user) do |form|
  - if admin_user.errors.any?
    div style="color: red"
      h2 = "#{pluralize(admin_user.errors.count, "error")} prohibited this admin_user from being saved:"
      ul
        - admin_user.errors.each do |error|
          li = error.full_message

  div
    = form.submit

app/views/admin/users/_user.html.slim
div id="#{dom_id user}"

app/views/admin/users/edit.html.slim
h1 Editing user

== render "form", admin_user: @admin_user

br

div
  => link_to "Show this user", @admin_user
  '|
  =< link_to "Back to users", admin_users_path

app/views/admin/users/index.html.slim
p style="color: green" = notice

h1 Users

#admin_users
  - @admin_users.each do |admin_user|
    == render admin_user
    p
      = link_to admin_user.full_name, admin_user_path(admin_user)

= link_to "New user", new_admin_user_path, class: 'btn btn-primary'

app/views/admin/users/new.html.slim
h1 New user

== render "form", admin_user: @admin_user

br

div
  = link_to "Back to users", admin_users_path

app/views/admin/users/show.html.slim
p style="color: green" = notice

== render @admin_user

div
  => link_to "Edit this user", edit_admin_user_path(@admin_user)
  '|
  =< link_to "Back to users", admin_users_path

  = button_to "Destroy this user", @admin_user, method: :delete

app/views/home/index.html.slim
.container
  h1 Вітаємо у нашому застосунку
  p Дякуємо за використання Ruby on Rails і Bootstrap!

  .btn.btn-primary Класична кнопка Bootstrap

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | OblMedStat
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = render "shared/header"
    .content
      p.notice
        = notice
      p.alert
        = alert
      = yield

app/views/shared/_header.html.slim
/ -------------------------------------------------------------------------------------------------
nav.navbar.navbar-expand-lg.navbar-light.bg-warning
  .container-fluid
    a.navbar-brand[href="#"]
      | OblMedStat
    button.navbar-toggler[type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      ul.navbar-nav
        li.nav-item
          = link_to "Головна", root_path, class: 'nav-link active', 'aria-current': 'page'
        - if user_signed_in?
          li.nav-item.dropdown
            a#dropdownMenuLink.btn.btn-warning.dropdown-toggle[href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"]
              | Особистий кабінет
            ul.dropdown-menu[aria-labelledby="dropdownMenuLink"]
              li
                = link_to "Редагувати профіль", edit_user_registration_path, class: 'dropdown-item'
              li
                = link_to "Щось інше", '#', class: 'dropdown-item'
              li.divider
              li
                = link_to "Вихід", destroy_user_session_path, method: :delete, class: 'dropdown-item'
        - else
          li = link_to "Увійти", new_user_session_path, class: 'nav-link'
          li = link_to "Зареєструватися", new_user_registration_path, class: 'nav-link '